In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Perceptron
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
with open("seeds_dataset.txt", "r") as file:
    content = file.read()

lines = content.split('\n')

data = [line.split('\t') [:8] 
        for line in lines]

df = pd.DataFrame(data)

df.head()

0      1       2      3      4      5      6  7
0  15.26  14.84   0.871  5.763  3.312  2.221   5.22  1
1  14.88  14.57  0.8811  5.554  3.333  1.018  4.956  1
2  14.29  14.09   0.905  5.291  3.337  2.699  4.825  1
3  13.84  13.94  0.8955  5.324  3.379  2.259  4.805  1
4  16.14  14.99  0.9034  5.658  3.562  1.355  5.175  1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       210 non-null    object
 1   1       210 non-null    object
 2   2       210 non-null    object
 3   3       210 non-null    object
 4   4       210 non-null    object
 5   5       210 non-null    object
 6   6       210 non-null    object
 7   7       210 non-null    object
dtypes: object(8)
memory usage: 13.3+ KB


In [4]:
df.columns

RangeIndex(start=0, stop=8, step=1)

In [5]:
df = df.rename(columns={0: 'f1', 1: 'f2', 2: 'f3', 3: 'f4', 4: 'f5', 5: 'f6', 6: 'f7', 7 : 'y'})
df

f1     f2      f3     f4     f5     f6     f7  y
0    15.26  14.84   0.871  5.763  3.312  2.221   5.22  1
1    14.88  14.57  0.8811  5.554  3.333  1.018  4.956  1
2    14.29  14.09   0.905  5.291  3.337  2.699  4.825  1
3    13.84  13.94  0.8955  5.324  3.379  2.259  4.805  1
4    16.14  14.99  0.9034  5.658  3.562  1.355  5.175  1
..     ...    ...     ...    ...    ...    ...    ... ..
205  12.19   13.2  0.8783  5.137  2.981  3.631   4.87  3
206  11.23  12.88  0.8511   5.14  2.795  4.325  5.003  3
207   13.2  13.66  0.8883  5.236  3.232  8.315  5.056  3
208  11.84  13.21  0.8521  5.175  2.836  3.598  5.044  3
209   12.3  13.34  0.8684  5.243  2.974  5.637  5.063  3

[210 rows x 8 columns]

In [6]:
df['y'] = df['y'].replace('', 0)
df['y'] = df['y'].astype(np.float64)
df['y'] = df['y'].astype(np.int64)

In [7]:
df[['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']] = df[['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']].replace('', 0)

In [8]:
df[['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']] = df[['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']].astype(np.float64)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   f1      210 non-null    float64
 1   f2      210 non-null    float64
 2   f3      210 non-null    float64
 3   f4      210 non-null    float64
 4   f5      210 non-null    float64
 5   f6      210 non-null    float64
 6   f7      210 non-null    float64
 7   y       210 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.3 KB


In [137]:
df['y'].value_counts()

2    69
1    66
3    65
5     4
0     4
4     2
Name: y, dtype: int64

In [90]:
df_2Y = df[(df['y']== 2) | (df['y']== 3)]
df_2Y.head()

f1     f2      f3     f4     f5     f6     f7  y
35  16.12  15.00  0.0000  0.900  0.000  5.709  3.485  2
70  17.63  15.98  0.8673  6.191  3.561  4.076  6.060  2
71  16.84  15.67  0.8623  5.998  3.484  4.675  5.877  2
72  17.26  15.73  0.8763  5.978  3.594  4.539  5.791  2
73  19.11  16.26  0.9081  6.154  3.930  2.936  6.079  2

In [91]:
df_2Y['y'].value_counts().sort_index()

2    69
3    65
Name: y, dtype: int64

In [92]:
x = df_2Y.iloc[:, :-1]
x

f1     f2      f3     f4     f5     f6     f7
35   16.12  15.00  0.0000  0.900  0.000  5.709  3.485
70   17.63  15.98  0.8673  6.191  3.561  4.076  6.060
71   16.84  15.67  0.8623  5.998  3.484  4.675  5.877
72   17.26  15.73  0.8763  5.978  3.594  4.539  5.791
73   19.11  16.26  0.9081  6.154  3.930  2.936  6.079
..     ...    ...     ...    ...    ...    ...    ...
205  12.19  13.20  0.8783  5.137  2.981  3.631  4.870
206  11.23  12.88  0.8511  5.140  2.795  4.325  5.003
207  13.20  13.66  0.8883  5.236  3.232  8.315  5.056
208  11.84  13.21  0.8521  5.175  2.836  3.598  5.044
209  12.30  13.34  0.8684  5.243  2.974  5.637  5.063

[134 rows x 7 columns]

In [93]:
y = df_2Y.iloc[:, -1]
y

35     2
70     2
71     2
72     2
73     2
      ..
205    3
206    3
207    3
208    3
209    3
Name: y, Length: 134, dtype: int64

In [94]:
y.value_counts()

2    69
3    65
Name: y, dtype: int64

In [95]:
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = .20, random_state= 42)

## Perseptron


In [96]:
# one layer nural network
perseptron = Perceptron()

perseptron

Perceptron()

In [97]:
perseptron.fit(x_train,y_train)

Perceptron()

In [98]:
perseptron_test = perseptron.predict(x_test)
confusion_matrix(y_test, perseptron_test)

array([[60,  0],
       [ 7, 41]], dtype=int64)

In [99]:
accuracy_score(y_test, perseptron_test) * 100

93.51851851851852

## SVM

In [100]:
svm  = SVC()

In [101]:
svm.fit(x_train,y_train)

SVC()

In [102]:
svm_test = svm.predict(x_test)

In [103]:
confusion_matrix(y_test, svm_test)

array([[57,  3],
       [ 0, 48]], dtype=int64)

In [104]:
accuracy_score(y_test, svm_test) * 100

97.22222222222221

#  OvR-Perceptron and OvR-SVM

In [105]:
with open("seeds_dataset.txt", "r") as file:
    content = file.read()

lines = content.split('\n')

data = [line.split('\t') [:8] 
        for line in lines]

df = pd.DataFrame(data)
df = df.rename(columns={0: 'f1', 1: 'f2', 2: 'f3', 3: 'f4', 4: 'f5', 5: 'f6', 6: 'f7', 7 : 'y'})
df['y'] = df['y'].replace('', 0)
df['y'] = df['y'].astype(np.float64)
df['y'] = df['y'].astype(np.int64)
df[['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']] = df[['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']].replace('', 0)
df[['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']] = df[['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']].astype(np.float64)


In [106]:
df_3Y = df[(df['y']==1) | (df['y']== 2) | (df['y'] == 3)]
df_3Y.head()

f1     f2      f3     f4     f5     f6     f7  y
0  15.26  14.84  0.8710  5.763  3.312  2.221  5.220  1
1  14.88  14.57  0.8811  5.554  3.333  1.018  4.956  1
2  14.29  14.09  0.9050  5.291  3.337  2.699  4.825  1
3  13.84  13.94  0.8955  5.324  3.379  2.259  4.805  1
4  16.14  14.99  0.9034  5.658  3.562  1.355  5.175  1

In [107]:
y_3 = df_3Y.iloc[:, -1]
x_3 = df_3Y.iloc[:, :-1]

In [108]:
df_3Y['y'].value_counts().sort_index()

1    66
2    69
3    65
Name: y, dtype: int64

In [109]:
x_train, x_test, y_train, y_test = train_test_split(x_3, y_3, train_size = .20, random_state= 42)

## OvR-Perceptron 

One-vs-Rest (OvR) strategy with Perceptron

In [110]:
from sklearn.datasets import make_classification
from sklearn.multiclass import OneVsRestClassifier

In [111]:
over_perceptron = OneVsRestClassifier(Perceptron())
over_perceptron.fit(x_train, y_train)

y_Over_prec = over_perceptron.predict(x_test)
accuracy_score(y_Over_prec, y_test) * 100


57.49999999999999

In [112]:
confusion_matrix(y_Over_prec, y_test)

array([[ 0,  0,  0],
       [54, 54, 14],
       [ 0,  0, 38]], dtype=int64)

### Improve Accuracy

In [113]:
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Perceptron
from sklearn.multiclass import OneVsRestClassifier

In [114]:
pipeline = Pipeline([
    ('scaler', StandardScaler()), 
    ('ovr_perceptron', OneVsRestClassifier(Perceptron()))   
])

# hyperparameters
param_grid = {
    # Regularization parameter
    'ovr_perceptron__estimator__alpha': [0.0001, 0.001, 0.01],  
    'ovr_perceptron__estimator__max_iter': [100, 200, 300],      
}

In [115]:
grid_search = GridSearchCV(pipeline, param_grid, cv = 10, scoring = 'accuracy')

grid_search.fit(x_train, y_train)


GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('ovr_perceptron',
                                        OneVsRestClassifier(estimator=Perceptron()))]),
             param_grid={'ovr_perceptron__estimator__alpha': [0.0001, 0.001,
                                                              0.01],
                         'ovr_perceptron__estimator__max_iter': [100, 200,
                                                                 300]},
             scoring='accuracy')

In [116]:
best_model = grid_search.best_estimator_
best_model

Pipeline(steps=[('scaler', StandardScaler()),
                ('ovr_perceptron',
                 OneVsRestClassifier(estimator=Perceptron(max_iter=100)))])

In [117]:
best_model.score(x_test, y_test) * 100


90.0

In [118]:
y_pred_per_multiclass =best_model.predict(x_test)
y_pred_per_multiclass

array([2, 1, 1, 3, 2, 2, 2, 3, 3, 1, 3, 3, 3, 2, 3, 3, 1, 3, 2, 2, 2, 1,
       3, 2, 1, 1, 2, 2, 2, 2, 3, 3, 1, 2, 3, 2, 3, 3, 3, 2, 2, 3, 3, 1,
       2, 3, 1, 1, 3, 2, 2, 3, 1, 2, 2, 2, 3, 2, 3, 2, 3, 2, 3, 1, 2, 2,
       2, 3, 2, 3, 3, 2, 3, 1, 2, 2, 1, 3, 2, 2, 1, 2, 1, 3, 1, 2, 3, 2,
       3, 3, 1, 3, 2, 1, 1, 3, 3, 1, 1, 1, 1, 1, 3, 3, 2, 3, 1, 1, 2, 3,
       3, 1, 3, 3, 2, 2, 1, 1, 3, 3, 1, 2, 3, 3, 1, 1, 3, 3, 2, 1, 3, 1,
       2, 3, 1, 3, 1, 2, 1, 2, 3, 3, 3, 1, 2, 3, 2, 2, 2, 2, 3, 3, 2, 2,
       1, 1, 3, 2, 1, 2], dtype=int64)

In [134]:
confusion_matrix(y_pred_per_multiclass, y_test)

array([[41,  1,  1],
       [ 5, 52,  0],
       [ 8,  1, 51]], dtype=int64)

In [133]:
# confusion_pred_per_multiclass = confusion_matrix(y_pred_per_multiclass, y_test)
# argmax(confusion_pred_per_multiclass, axis=0)


array([0, 1, 2], dtype=int64)

## OvR-SVM 



In [120]:
over_svm = OneVsRestClassifier(SVC(kernel='linear'))
over_svm.fit(x_train, y_train)
y_pred_over_svm = over_svm.predict(x_test)


In [121]:
accuracy_score(y_pred_over_svm, y_test) * 100

90.0

In [135]:
confusion_matrix(y_pred_over_svm, y_test)

array([[42,  2,  2],
       [ 7, 52,  0],
       [ 5,  0, 50]], dtype=int64)

In [122]:
y_pred_over_svm

array([2, 3, 1, 3, 2, 2, 2, 3, 3, 1, 3, 3, 3, 2, 3, 3, 1, 3, 2, 2, 2, 1,
       3, 2, 1, 1, 2, 2, 2, 2, 2, 3, 1, 2, 3, 2, 3, 3, 3, 2, 2, 3, 3, 1,
       2, 3, 1, 1, 3, 2, 2, 3, 1, 2, 2, 2, 3, 2, 3, 2, 3, 2, 1, 1, 2, 2,
       2, 3, 2, 3, 2, 2, 3, 1, 2, 2, 1, 3, 2, 2, 1, 2, 1, 3, 1, 2, 3, 2,
       3, 3, 1, 3, 2, 1, 1, 3, 3, 1, 1, 1, 1, 1, 3, 3, 2, 3, 1, 1, 2, 3,
       3, 1, 3, 3, 2, 2, 1, 1, 3, 1, 1, 2, 3, 3, 1, 1, 3, 3, 2, 1, 3, 1,
       2, 3, 1, 3, 1, 2, 1, 2, 3, 3, 3, 1, 2, 1, 2, 2, 2, 2, 3, 3, 2, 2,
       1, 1, 1, 2, 1, 2], dtype=int64)

In [123]:
# import matplotlib.pyplot as plt
# plt.figure(figsize=(10, 5))
# plt.scatter(x_test[y_test == y_Over_prec, 1], x_test[y_test == y_Over_prec, 2], c='green', label='Correct')
# plt.scatter(x_test[y_test != y_Over_prec, 1], x_test[y_test != y_Over_prec, 2], c='red', label='Wrong')
# plt.xlabel("Feature 1")
# plt.ylabel("Feature 2")
# plt.title("Perceptron: Correct vs. Wrong Predictions")
# plt.legend()
# plt.show()


In [136]:
# # numpy implementation of argmax
# from numpy import argmax, asarray
# # define vector
# probs = asarray([[5, 0.5, 0.1], [0.0, 6.0, 1.0], [0.9, 0.0, 0.1], [0.3, 0.3, 0.4]])

# result = argmax(probs, axis=1)
# print(result)

In [124]:
# # Assuming we have the probability scores for each class from each classifier
# # Let's denote these scores as perceptron_prob_scores and svm_prob_scores for OvR-Perceptron and OvR-SVM respectively

# # Aggregate probability scores
# aggregated_prob_scores = (perceptron_prob_scores + svm_prob_scores) / 2  # Taking the mean

# # Obtain final predictions
# final_predictions = np.argmax(aggregated_prob_scores, axis=1)

# # Calculate accuracy
# aggregated_accuracy = accuracy_score(y_test, final_predictions)

# # Generate confusion matrix
# aggregated_conf_matrix = confusion_matrix(y_test, final_predictions)




NameError: name 'perceptron_prob_scores' is not defined

In [ ]:
# # Plot correct and wrong prediction points
# plt.figure(figsize=(8, 6))
# plt.scatter(x_test[final_predictions == y_test][:, 0], 
#             x_test[final_predictions == y_test][:, 1], 
#             c='green', label='Correct Predictions')
# plt.scatter(x_test[final_predictions != y_test][:, 0], 
#             x_test[final_predictions != y_test][:, 1], 
#             c='red', label='Wrong Predictions')
# plt.title('Aggregated Strategy Correct vs. Wrong Predictions')
# plt.xlabel('Feature 1')
# plt.ylabel('Feature 2')
# plt.legend()
# plt.show()

# # Print results
# print("Aggregated Strategy Accuracy:", aggregated_accuracy)
# print("Aggregated Strategy Confusion Matrix:")
# print(aggregated_conf_matrix)